see how function works
fhdsl/anvilPoll2024 pull request #29
Opened 2024-05-21 21:11 UTC by kweav

2024-05-22 03:47 UTC, kweav commented
The preview took a while to render last time since we knit the tidy data rmarkdown a couple of times. I imagine it'll take a lot longer this time with even more pages all re-knitting it. It may be worth knitting it once and writing it out/reading it in for each page depending on how long it takes/how long we're comfortable with it taking?

2024-05-22 17:04 UTC, kweav commented
Fetched changes from main to fix spelling errors -- the commit history reflects that and my attempts to resolve an issue with a file that had changes in main, but I had deleted (`IdentifyTypeOfUsers.Rmd` -- not the one in `pages` directory).

2024-05-22 18:13 UTC, kweav commented
Merged main which incorporated #31 with a custom docker to speed up preview rendering

2024-05-22 18:21 UTC, kweav commented
[Latest commit ce31139](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/ce31139d020123cf535ef7001cd91fa26446fe31) adds the new pages to the `_site.yml` .

2024-05-30 18:42 UTC, avahoffman requested changes
It's really coming together! Please let me know if you have questions on any of the suggestions.

2024-05-30 18:42 UTC, avahoffman commented on resources/scripts/shared_functions.R
> +          legend.position = "inside",
```suggestion
          legend.position = c(0.8, 0.8)
```
I got an error `The 'legend.position.inside' theme element is not defined in the element hierarchy.` when running with arg `legend.position.inside` . I think you can specify the position like this, but I'd test to make sure.

2024-05-30 18:42 UTC, avahoffman commented on pages/Preferences.Rmd
> +Institutional HPC and locally/personal computers are the most common responses. Google Cloud Platform (GCP) is reported as used more than Amazon Web Services (AWS) within this sample. We also see tha
```suggestion
Institutional HPC and locally/personal computers are the most common responses. Google Cloud Platform (GCP) is reported as used more than other cloud providers within this sample. We also see that potential users report using Galaxy (a free option) more than current users do. 
```

2024-05-30 18:42 UTC, avahoffman commented on pages/_site.yml
>    - text: "Current User Specific Questions"
```suggestion
  - text: "Current Users"
```

2024-05-30 19:06 UTC, kweav commented on pages/Demographics.Rmd
> +                  aes(label = after_stat(x), group = FurtherSimplifiedDegrees),
I have tried adding it to the stylize function previously because I completely agree with you -- I think I have to pass the function `resultsTidy` since `geom_text()` uses `aes`. I'll try it again and see if I have better luck this time. For time's sake, I hadn't resolved that yet.

2024-05-30 19:08 UTC, kweav commented on pages/Demographics.Rmd
> +## Takeaway
Lol glad you agree! Will happily remove

2024-05-30 19:31 UTC, kweav commented on pages/Demographics.Rmd
> +consortiaTable[which(consortiaTable$count >1),]
Do I need to load the kableExtra package?

2024-05-30 19:32 UTC, kweav commented on pages/Demographics.Rmd
> +consortiaTable[which(consortiaTable$count >1),]
Thank you -- this table will look so much nicer!

2024-05-30 19:34 UTC, kweav commented on pages/Experience.Rmd
> +Except for Galaxy, potential users tend to report lower comfort levels for the various tools and technologies (separate from the AnVIL) when compared to current users also reporting their comfort lev
And thank you for adding the note about similar comfort levels for current users on and off the AnVIL!

2024-05-30 19:38 UTC, kweav commented on pages/Experience.Rmd
> +Of the survey provided choices, respondents were particularly interested in accessing All of Us, UK Biobank, and GTEx (though All of Us and UK Biobank are not currently AnVIL hosted). 2 respondents (
Great idea! Will try to add some links for that

2024-05-30 19:40 UTC, kweav commented on resources/scripts/shared_functions.R
> +          legend.position = "inside",
Hm, I know I had a struggle with this when I first tried to move the legends inside using only the numbers, and it told me what I was trying to use was deprecated. Could it be a version difference?

2024-05-30 19:46 UTC, kweav commented on pages/Demographics.Rmd
> +consortiaTable[which(consortiaTable$count >1),]
> Do I need to load the kableExtra package?

Yes, I do need to. Render is failing without it. Will do

2024-05-30 19:54 UTC, avahoffman commented on resources/scripts/shared_functions.R
> +          legend.position = "inside",
Ok let's leave as is with a commented note in the function. I know the container uses a different version of R than I have so you're probably right. Does it work locally for you?

2024-05-30 20:17 UTC, kweav commented on resources/scripts/shared_functions.R
> +          legend.position = "inside",
Yes it does

2024-05-30 20:57 UTC, kweav commented on pages/CurrentUserQs.Rmd
> +  ggplot(aes(x = RecommendationLikelihood, y = count, fill = as.factor(RecommendationLikelihood))) + geom_bar(stat="identity") +
Tried to fix throughout in [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4)

2024-05-30 20:57 UTC, kweav commented on pages/CurrentUserQs.Rmd
> +knitr::knit_child(here("TidyData.Rmd")) #inherit resultsTidy
Addressed in [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4)

2024-05-30 20:58 UTC, kweav commented on pages/Demographics.Rmd
> +source(here("resources/scripts/shared_functions.R"))
Addressed in [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4)

2024-05-30 20:58 UTC, kweav commented on pages/Demographics.Rmd
> +                  aes(label = after_stat(x), group = FurtherSimplifiedDegrees),
Added number labels directly to plots for now in [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4). Will add as part of functions in a later commit.

2024-05-30 20:59 UTC, kweav commented on pages/Experience.Rmd
> +knitr::knit_child(here("TidyData.Rmd")) #inherit resultsTidy
Addressed in the [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4)

2024-05-30 20:59 UTC, kweav commented on pages/IdentifyTypeOfUsers.Rmd
> +knitr::knit_child(here("TidyData.Rmd")) #inherit resultsTidy
Addressed in the [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4)

2024-05-30 20:59 UTC, kweav commented on pages/Preferences.Rmd
> +knitr::knit_child(here("TidyData.Rmd")) #inherit resultsTidy
Addressed in the [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4)

2024-05-30 21:03 UTC, kweav commented on pages/Demographics.Rmd
> +consortiaTable[which(consortiaTable$count >1),]
Added `library(kableExtra)` in [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4)

2024-05-30 21:04 UTC, kweav commented on pages/Experience.Rmd
> +Of the survey provided choices, respondents were particularly interested in accessing All of Us, UK Biobank, and GTEx (though All of Us and UK Biobank are not currently AnVIL hosted). 2 respondents (
Added some potential links in [latest commit](https://github.com/fhdsl/anvilPoll2024/pull/29/commits/68ece2374f2f3fca62173067b5553e7aec35f6a4)

2024-05-30 21:20 UTC, avahoffman approved these changes

2024-05-30 21:34 UTC, merged